name: Daily Journal Push
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:      # 必须有这一行，且缩进与 schedule 对齐

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          PUSHDEER_KEY: ${{ secrets.PUSHDEER_KEY }}
        run: python main.py
